### ISSUE TITLE
Use of "normal" to describe patients

### ISSUE THREAD

**Issue by MelanieIStefan** [carpentries-incubator/machine-learning-novice-python#8]
<details>
<summary><strong>Use of "normal" to describe patients</strong></summary>

This is a bit nit-picky, but in talking about imputing missing data, the word "normal" is equated with healthy when talking about patient data. I usually avoid using "normal" since it can carry ableist connotations.

</details>

**Comment by tompollard** [comment]
Thanks for raising this Melanie, important point. We'll get this fixed.

**Comment by tompollard** [comment]
Fixed in https://github.com/carpentries-incubator/machine-learning-novice-python/commit/e187d29e4141df588393a79010b7ebffa3d19ab7
